import pandas as pd
import numpy as np
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))

from inference import run_inference, _ensure_loaded
from features.arbitrage_scanner import scan_pure_arbitrage, scan_statistical_arbitrage

def get_real_outcome(h_goals, a_goals):
    if h_goals > a_goals: return 'H'
    elif a_goals > h_goals: return 'A'
    return 'D'

def backtest_historical():
    _ensure_loaded(is_live=False)
    
    df = pd.read_csv('data/international_results.csv')
    wc_2026 = df[(df['tournament'] == 'FIFA World Cup') & (df['date'] >= '2026-06-01')].copy()
    wc_2026 = wc_2026.dropna(subset=['home_score', 'away_score'])
    wc_2026 = wc_2026.sort_values('date')
    
    bankroll_inr = 1000.0
    ledger = []
    
    for i, row in wc_2026.iterrows():
        home = row['home_team']
        away = row['away_team']
        date = row['date']
        
        real_h = int(row['home_score'])
        real_a = int(row['away_score'])
        real_outcome = get_real_outcome(real_h, real_a)
        
        # 1. Get Model Predictions
        res = run_inference(home, away)
        prob_h = res['home_win_prob']
        prob_d = res['draw_prob']
        prob_a = res['away_win_prob']
        
        # 2. Retrieve Bookmaker Odds (Market)
        # Using the baseline historical odds generated by odds_engineer
        try:
            baseline_df = pd.read_csv('scratch/historical_odds_baseline.csv')
            match_odds = baseline_df[(baseline_df['home_team'] == home) & (baseline_df['away_team'] == away)]
            if len(match_odds) > 0:
                market_h = match_odds.iloc[0]['market_h']
                market_d = match_odds.iloc[0]['market_d']
                market_a = match_odds.iloc[0]['market_a']
            else:
                # Fallback if somehow missing
                market_h = max(1.01, (1 / max(prob_h, 0.01)) * 0.95)
                market_d = max(1.01, (1 / max(prob_d, 0.01)) * 0.95)
                market_a = max(1.01, (1 / max(prob_a, 0.01)) * 0.95)
        except FileNotFoundError:
            # Fallback
            market_h = max(1.01, (1 / max(prob_h, 0.01)) * 0.95)
            market_d = max(1.01, (1 / max(prob_d, 0.01)) * 0.95)
            market_a = max(1.01, (1 / max(prob_a, 0.01)) * 0.95)
        
        # 3. Arbitrage Scanners
        df_match = pd.DataFrame([{
            'max_h': market_h, 'max_d': market_d, 'max_a': market_a
        }])
        
        df_match = scan_pure_arbitrage(df_match)
        df_match = scan_statistical_arbitrage(df_match, pd.Series([prob_h]), pd.Series([prob_d]), pd.Series([prob_a]), bankroll=bankroll_inr)
        
        bet_row = df_match.iloc[0]
        
        pnl = 0.0
        stake_h, stake_d, stake_a = 0.0, 0.0, 0.0
        bet_type = "None"
        
        # Settle Pure Arbitrage
        if bet_row['is_pure_arb']:
            bet_type = "Pure Arb"
            arb_stake_h = bankroll_inr * bet_row.get('arb_stake_h_pct', 0.0)
            arb_stake_d = bankroll_inr * bet_row.get('arb_stake_d_pct', 0.0)
            arb_stake_a = bankroll_inr * bet_row.get('arb_stake_a_pct', 0.0)
            
            arb_cost = arb_stake_h + arb_stake_d + arb_stake_a
            if real_outcome == 'H': arb_payout = arb_stake_h * market_h
            elif real_outcome == 'D': arb_payout = arb_stake_d * market_d
            else: arb_payout = arb_stake_a * market_a
            
            pnl += (arb_payout - arb_cost)
            stake_h, stake_d, stake_a = arb_stake_h, arb_stake_d, arb_stake_a
            
        else:
            # Settle Statistical Edge
            stake_h = bet_row.get('stake_h', 0.0)
            stake_d = bet_row.get('stake_d', 0.0)
            stake_a = bet_row.get('stake_a', 0.0)
            
            if stake_h > 0 or stake_d > 0 or stake_a > 0:
                bet_type = "Stat Edge"
                if stake_h > 0:
                    if real_outcome == 'H': pnl += stake_h * (market_h - 1)
                    else: pnl -= stake_h
                if stake_d > 0:
                    if real_outcome == 'D': pnl += stake_d * (market_d - 1)
                    else: pnl -= stake_d
                if stake_a > 0:
                    if real_outcome == 'A': pnl += stake_a * (market_a - 1)
                    else: pnl -= stake_a

        bankroll_inr += pnl
        
        ledger.append({
            "Date": date,
            "Match": f"{home} vs {away}",
            "Score": f"{real_h}-{real_a}",
            "Real Outcome": real_outcome,
            "Model (H/D/A)": f"{prob_h:.2f}/{prob_d:.2f}/{prob_a:.2f}",
            "Odds (H/D/A)": f"{market_h:.2f}/{market_d:.2f}/{market_a:.2f}",
            "Bet Type": bet_type,
            "Stake (INR)": round(stake_h + stake_d + stake_a, 2),
            "PnL (INR)": round(pnl, 2),
            "Bankroll (INR)": round(bankroll_inr, 2)
        })

    # Save artifact
    res_df = pd.DataFrame(ledger)
    
    import os
    artifact_dir = "C:/Users/MMS Mandapeta/.gemini/antigravity/brain/3b87df0b-690d-4948-9190-44b802ca1365"
    with open(os.path.join(artifact_dir, 'historical_arbitrage_balance_sheet.md'), 'w', encoding='utf-8') as f:
        f.write("# Historical Arbitrage Backtest\n\n")
        f.write(f"**Starting Bankroll:** 1000 INR\n")
        f.write(f"**Final Bankroll:** {bankroll_inr:.2f} INR\n")
        f.write(f"**Total ROI:** {((bankroll_inr - 1000) / 1000) * 100:.2f}%\n\n")
        
        f.write("### Ledger\n\n")
        try:
            f.write(res_df.to_markdown(index=False))
        except ImportError:
            for col in res_df.columns:
                f.write(f"| {col} ")
            f.write("|\n")
            f.write("|---" * len(res_df.columns) + "|\n")
            for idx, row in res_df.iterrows():
                for col in res_df.columns:
                    f.write(f"| {row[col]} ")
                f.write("|\n")

if __name__ == "__main__":
    backtest_historical()
    print("Done!")
